---
  # See appveyor.yml for windows build.
  sudo: false
  language: go
  os:
    - osx
  notifications:
    email: false
  go:
    - 1.6
  install: make deps
  before_script: make validate
  script: make test

  before_deploy:
    - mkdir bin
    - go build -o bin/docker-credential-osxkeychain osxkeychain/cmd/main_darwin.go
    - cd bin
    - tar czf ../docker-credential-osxkeychain-${TRAVIS_TAG}-amd64.tar.gz docker-credential-osxkeychain

  deploy:
    provider: releases
    api_key:
      secure: "cGs5cao/MeVQVnum+Pr/Tpv+w83NsqGVS3wxvi3LYEf2ON4Kkmtd+Alwi0YFkGPJmSY0jZOct8NVK/M70qSnIU4l+AAq9+3KSMv23u4xrmy2sQog3AF+Ve3Rac+iYwZHOWwGs9I67CSuVv0vjJNVsDsTVefc25lHJImjRvXIS4p9xYzRPeUDCoqAo/QMVE+vFiMyxydsvt8fhd0gZCjPYWEpyHe9tjZ1tr1HsHZKFAjVb6AmF45d8rvadPoVUuLaOtr35wDC3XRKEvCZUefQpwLkrNj7j2L1rVGlY1xTE2APpLtvfd7R1Mx6kSfS1Gm3Pwcv3mugadXIhecL0lsdnU+BANjX3VUiv4ryzTPbsge966mv9ZQYwAzgCQTWRtMNJqsAnPZTeAkiOntd+HMQbPpxljOxv1sjDPY+EIZesyB3yQRJI8vMxqFcAjxeRyLcBqEnRFC2nd/Ln0KZ7ZFu16FcpNqRojdBayyypuXKqAiBNwtp4ti/65x8eHfBJuNjJtNZkRsJEYam4CYMRLxds9plKQfkaZ8045PKpyXO8fMpUhrfqSVID4IrYvD+io6XoXtdR4Lk6isZ2EgrjdrqgdG70S5lwKihL4iAi2F2ZCWhngFhkeNVOZunEWE6qZMk5wKODajR9sixGDApGPZQVojHwCNRGILZaHZ39JCIj3s="
    file: docker-credential-osxkeychain-${TRAVIS_TAG}-amd64.tar.gz
    # don't delete the artifacts from previous phases
    skip_cleanup: true
    # deploy when a new tag is pushed
    on:
      tags: true
  
  branches:
    only:
      # Pushes and PR to the master branch
      - master
      # IMPORTANT Ruby regex to match tags. Required, or travis won't trigger deploys when a new tag
      # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
      - /^v\d+\.\d+\.\d+.*$/
