version: "3.9"

services:
  nginx:
    # Note : Only nginx:alpine supports bcrypt.
    # If you don't need to use bcrypt, you can use a different tag.
    # Ref. https://github.com/nginxinc/docker-nginx/issues/29
    image: "nginx:alpine"
    ports:
      - 5043:443
    links:
      - registry:registry
    volumes:
      - ./registry/auth:/etc/nginx/conf.d
      - ./registry/auth/nginx.conf:/etc/nginx/nginx.conf:ro

  registry:
    container_name: docker-registry
    image: registry:2
    volumes:
      - ./registry/data:/var/lib/registry

  auth-server:
    container_name: authserver
    build: ./registry/auth-server
    command: npm run start
    ports:
      - 8000:8000
    volumes:
      - ./registry/auth-server/src:/app/src